export const currentData = [
  {
    id: 1,
    company: "JIVITHA AYURVEDA",
    contact: "Manager",
    address: "Office No.11, 5th floor dawa bazar, INDORE (M.P) 452001",
    cards: [
      { name: "adivasioil", image: "/final jivitha pics/adivasioil.png" },
      { name: "allergyoil", image: "/final jivitha pics/allergy.png" },
      { name: "applecider", image: "/final jivitha pics/applecider.png" },
      { name: "fatcure", image: "/final jivitha pics/fatcure.png" },
      { name: "gutne", image: "/final jivitha pics/ghutne.png" },
      { name: "mushroom", image: "/final jivitha pics/mushroonpowder.png" },
      { name: "proteeplus", image: "/final jivitha pics/proteeplus.png" },
      { name: "SugerKipakki", image: "/final jivitha pics/sugarkipakki.png" },
    ],
    area: "Indore",
    imageLogo: "/companyLogo/jivithalogo.png",
    licenseNo: "MP/25D/10/111",
    validUpto: "14/06/2023",
  },
  {
    id: 2,
    company: "APEX HERBAL",
    contact: "Manager",
    address: "299 SANT NAGAR KHANDWA ROAD INDORE (M.P.)",
    cards: [
      { name: "All Products", image: "/productsPage/product/allproducts.png" },
      { name: "Ayurvedic Oils", image: "/productsPage/product/ayurvedicoils.png" },
      { name: "Capsule", image: "/productsPage/product/capsule.png" },
      { name: "Gel Balm", image: "/productsPage/product/gelbalm.png" },
      { name: "Hair Oil", image: "/productsPage/product/hairoil.png" },
      { name: "Herbal", image: "/productsPage/product/herbal.png" },
      { name: "Syrup", image: "/productsPage/product/syrup.png" },
    ],
    area: "Indore",
    imageLogo: "/companyLogo/logo1.png",
    licenseNo: "MP/25D/13/241",
    validUpto: "15/12/2023",
  },
  {
    id: 3,
    company: " ANUJ HERBALS PRODUCTS",
    contact: "Manager",
    address: "MAIN ROAD BURHAR DISTT SHAHDOL",
    product: "Herbal Products",
    cards : [
      { name: "All Products", image: "/productsPage/product/allproducts.png" },
      { name: "Ayurvedic Oils", image: "/productsPage/product/ayurvedicoils.png" },
      { name: "Capsule", image: "/productsPage/product/capsule.png" },
      { name: "Gel Balm", image: "/productsPage/product/gelbalm.png" },
      { name: "Hair Oil", image: "/productsPage/product/hairoil.png" },
      { name: "Herbal", image: "/productsPage/product/herbal.png" },
      { name: "Syrup", image: "/productsPage/product/syrup.png" },
      // Add more cards as needed
    ],
    area: "Shahdol",
    imageLogo: "/companyLogo/logo1.png",
    licenseNo: "MP/25D/11/164",
    validUpto: "03/10/2024"
  },
  {
    id: 4,
    company: " AMMMI PHARMACEUTICALS",
    contact: "Manager",
    address: "2-DR. LAGAN COMPOUND, SEHORE-1",
    product: "Pharmaceuticals",
    cards : [
      { name: "All Products", image: "/productsPage/product/allproducts.png" },
      { name: "Ayurvedic Oils", image: "/productsPage/product/ayurvedicoils.png" },
      { name: "Capsule", image: "/productsPage/product/capsule.png" },
      { name: "Gel Balm", image: "/productsPage/product/gelbalm.png" },
      { name: "Hair Oil", image: "/productsPage/product/hairoil.png" },
      { name: "Herbal", image: "/productsPage/product/herbal.png" },
      { name: "Syrup", image: "/productsPage/product/syrup.png" },
      // Add more cards as needed
    ],
    area: "Sehore",
    imageLogo: "/companyLogo/logo1.png",
    licenseNo: "25D/13/81",
    validUpto: "31/12/2026"
  },
  {
    id: 5,
    company: "ADARSH PHARMACEUTICALS",
    contact: "Manager",
    address: "POST OFFICE BARIATHA, SAGAR",
    product: "Pharmaceuticals",
    cards : [
      { name: "All Products", image: "/productsPage/product/allproducts.png" },
      { name: "Ayurvedic Oils", image: "/productsPage/product/ayurvedicoils.png" },
      { name: "Capsule", image: "/productsPage/product/capsule.png" },
      { name: "Gel Balm", image: "/productsPage/product/gelbalm.png" },
      { name: "Hair Oil", image: "/productsPage/product/hairoil.png" },
      { name: "Herbal", image: "/productsPage/product/herbal.png" },
      { name: "Syrup", image: "/productsPage/product/syrup.png" },
      // Add more cards as needed
    ],
    area: "Sagar",
    imageLogo: "/companyLogo/logo1.png",
    licenseNo: "25D/7/89",
    validUpto: "31/12/2027"
  },
  {
    id: 6,
    company: "ANGLO SWIFT MEDI SCIENCE",
    contact: "Manager",
    address: "119 - INDUSTRIAL AREA, DEWAS ROAD UJJAIN",
    product: "Medical Products",
    cards : [
      { name: "All Products", image: "/productsPage/product/allproducts.png" },
      { name: "Ayurvedic Oils", image: "/productsPage/product/ayurvedicoils.png" },
      { name: "Capsule", image: "/productsPage/product/capsule.png" },
      { name: "Gel Balm", image: "/productsPage/product/gelbalm.png" },
      { name: "Hair Oil", image: "/productsPage/product/hairoil.png" },
      { name: "Herbal", image: "/productsPage/product/herbal.png" },
      { name: "Syrup", image: "/productsPage/product/syrup.png" },
      // Add more cards as needed
    ],
    area: "Ujjain",
    imageLogo: "/companyLogo/logo1.png",
    licenseNo: "MP/25D/14/344",
    validUpto: "14/01/2027"
  },
  {
    id: 7,
    company: " AYURVEDIC HERBALS PRODUCTS RESEARCH CENTER",
    contact: "Manager",
    address: "KHASRA NO 162,NEAR POLICE STATION GHUGHRI DISTT MANDLA",
    product: "Ayurvedic Products",
    card : [
      { name: "All Products", image: "/productsPage/product/allproducts.png" },
      { name: "Ayurvedic Oils", image: "/productsPage/product/ayurvedicoils.png" },
      { name: "Capsule", image: "/productsPage/product/capsule.png" },
      { name: "Gel Balm", image: "/productsPage/product/gelbalm.png" },
      { name: "Hair Oil", image: "/productsPage/product/hairoil.png" },
      { name: "Herbal", image: "/productsPage/product/herbal.png" },
      { name: "Syrup", image: "/productsPage/product/syrup.png" },
      // Add more cards as needed
    ],
    area: "Mandla",
    imageLogo: "/companyLogo/logo1.png",
    licenseNo: "MP25D/08/050",
    validUpto: "23/09/2025"
  },
  {
    id: 8,
    company: " ARVIND BROTHERS",
    contact: "Manager",
    address: "32-DOODH TALAI ROAD, PADAWA, KHANDWA",
    product: "Ayurvedic Products",
    area: "Khandwa",
    imageLogo: "/companyLogo/logo1.png",
    licenseNo: "AYUR 33D/77",
    validUpto: "01/12/2027"
  },
  {
    id: 9,
    company: "ASTAVAKRA AYURVED",
    contact: "Manager",
    address: "SK 1 COMPOUND LASUDIA MORI NEAR DHANIYA FACTORY DEWAS NAKA INDORE (M.P.)",
    product: "Ayurvedic Products",
    area: "Indore",
    imageLogo: "/companyLogo/logo1.png",
    licenseNo: "MP25D/18/599",
    validUpto: "03/04/2023"
  },
  {
    id: 10,
    company: " ARCHNA PHARMACEUTICAL",
    contact: "Manager",
    address: "PLOT NO.-76/33, INDUSTRIAL AREA, MAXI ROAD, UJJAIN",
    product: "Pharmaceuticals",
    area: "Ujjain",
    imageLogo: "/companyLogo/logo1.png",
    licenseNo: "25D/28/2001",
    validUpto: "12/09/2024"
  },
  {
    id: 11,
    company: " ALCHEMY CHEMICALS",
    contact: "Manager",
    address: "31/6-INDUSTRIAL RAEA, MAXI ROAD, UJJAIN",
    product: "Chemicals",
    area: "Ujjain",
    imageLogo: "/companyLogo/logo1.png",
    licenseNo: "25D/32/99",
    validUpto: "26/09/2024"
  },
  {
    id: 12,
    company: "AMAZE LIFE CARE",
    contact: "Manager",
    address: "234-RAMBALI NAGAR, INDORE (M.P.)",
    product: "Healthcare Products",
    area: "Indore",
    imageLogo: "/companyLogo/logo1.png",
    licenseNo: "MP/25D/14/335",
    validUpto: "05/08/2024"
  },
  {
    id: 13,
    company: "ABL HEALTH CARE AYURVEDIC",
    contact: "Manager",
    address: "311-KHANDELWAL COMPOUND, PALDA, INDORE",
    product: "Ayurvedic Products",
    area: "Indore",
    imageLogo: "/companyLogo/logo1.png",
    licenseNo: "MP/25D/14/305",
    validUpto: "26/03/2024"
  },
  {
    id: 14,
    company: "AMIT AYURVDIC PHARMACY",
    contact: "Manager",
    address: "150 SHASTRI VIHAR JABALPUR",
    product: "Ayurvedic Products",
    area: "Jabalpur",
    imageLogo: "/companyLogo/logo1.png",
    licenseNo: "25D/16/89",
    validUpto: "31/12/2025"
  },
  {
    id: 15,
    company: " ADIDEV NATURALS",
    contact: "Manager",
    address: "1495 LIGHT TOWN, NEAR STADIUM JABALPUR",
    product: "Natural Products",
    area: "Jabalpur",
    imageLogo: "/companyLogo/logo1.png",
    licenseNo: "25D/35/2005",
    validUpto: "06/10/2024"
  },
  {
    id: 16,
    company: " ANJANI PHARMACEUTICAL",
    contact: "Manager",
    address: "51 NEAR INDUSTRIAL AREA MANDIDEEP RAISEN",
    product: "Pharmaceuticals",
    area: "Raisen",
    imageLogo: "/companyLogo/logo1.png",
    licenseNo: "25D/23/90",
    validUpto: "13/06/2024"
  },
  {
    id: 17,
    company: "AMSAR GOA PVT LTD",
    contact: "Manager",
    address: "5/11 MAHESH NAGAR, INDORE",
    product: "Pharmaceutical Products",
    area: "Indore",
    imageLogo: "/companyLogo/logo1.png",
    licenseNo: "MP/25D/13/244",
    validUpto: "14/05/2023"
  },
  {
    id: 18,
    company: "AYUVERDHANAM PHARMACEUTICALS",
    contact: "Manager",
    address: "WARD NO.-4 VILLAGE BAGUTA CHAATARPUR",
    product: "Ayurvedic Products",
    area: "Chaatarpur",
    imageLogo: "/companyLogo/logo1.png",
    licenseNo: "MP/25D/11/136",
    validUpto: "16/03/2024"
  }

];